core/urls.py
from django.urls import path,re_path
from .views import  PhotoListView,PhotoDetailView,PhotoCreateView,PhotoUpdateView,PhotoDeleteView,PhotoTagListView,PhotoSearchView
   

app_name = 'core'
urlpatterns = [
   path('',PhotoListView.as_view(),name='list'),
    path('create/',PhotoCreateView.as_view(),name='create'),
    path('photo/<slug:slug>/',PhotoDetailView.as_view(),name='detail'),
    path('photo/<slug:slug>/update/',PhotoUpdateView.as_view(),name='update'),
    path('photo/<slug:slug>/delete/',PhotoDeleteView.as_view(),name='delete'),
    path('tag/<slug:tag>/',PhotoTagListView.as_view(),name='tag'),
    re_path(r'^search/(\w+)/$', PhotoSearchView.as_view(),name='search'),
]

photoshare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
    path('users/',include('users.urls',namespace='users')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


core/models.py
from urllib import request
from django.db import models
from taggit.managers import TaggableManager
from django.utils.text import slugify
from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCountMixin,HitCount
#from ipware import get_client_ip
import random
import geocoder



# Create your models here.

Token ='pk.eyJ1IjoiaWVueWVuZSIsImEiOiJjbDVwYzV3bW0wcmp6M2lvZWRmamN4cnV3In0.G3yaMn224wCZg4kS1CMbnQ'

class Photo(models.Model,HitCountMixin):
    title =models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='photos')
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='photo_user')
    tags = TaggableManager()
    location = models.CharField(max_length=200, blank=True)
    lat = models.FloatField(blank=True, null=True)
    lon = models.FloatField(blank=True, null=True)
    hit_count_generic = GenericRelation(HitCount,object_id_field='object_pk',
    related_query_name='hit_count_generic_relation')
    # location TODOO
    #def get_absolute_url(self):
        #return reverse('photo_detail', args=[self.slug])

    def current_hit_count(self):
        return self.hit_count_generic.hit_count()

    def __str__(self):
        return self.title

    def save(self,*args,**kwargs):
        self.slug = slugify(self.title + "-" + str(random.randint(10000,99999)))
        g =geocoder.mapbox(self.location,key=Token)
        g = g.latlng
        self.lat = g[0]
        self.lon = g[1]
        super(Photo,self).save(*args,**kwargs)

    class Meta:
        ordering = ['-created']

# def get_client_ip(request):
#     x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
#     if x_forwarded_for:
#         ip = x_forwarded_for.split(',')[-1].strip()
#     else:
#         ip = request.META.get('REMOTE_ADDR')
#     return ip

# class ViewedPhoto(models.Model):
#     photo = models.ForeignKey(Photo, on_delete=models.CASCADE, related_name='viewed_photo')
#     ip = models.CharField(max_length=20)
    

#     def __str__(self):
#         return self.photo.title

#     def post_view(self):
#         viewed_photo,created = ViewedPhoto.objects.get_or_create(photo=self.photo)
#         if created:
#             counter = viewed_photo.photo.count
#             counter += 1
#             return counter
#         return False

core/views.py
from django.shortcuts import render,get_object_or_404
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from . models import Photo

from hitcount.models import HitCount
from hitcount.views import HitCountMixin

# Create your views here.
def home(request):
    return render(request, 'home.html')

import requests

url = "https://google-maps-search1.p.rapidapi.com/place-photos"

querystring = {"google_id":"0x89c259b5a9bd152b:0x31453e62a3be9f76","limit":"5"}

headers = {
	"X-RapidAPI-Key": "1a9e7fd576mshb3fa339ddb0b6c1p1edfdajsnb94f8d3f94fe",
	"X-RapidAPI-Host": "google-maps-search1.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)

#count = ViewedPhoto.post_view(self=ViewedPhoto)

class PhotoListView(ListView):
    model = Photo
    template_name = 'core/list.html'
    context_object_name = 'photos'
   


# class PhotoSearchListView(ListView):
#     model = Photo
#     template_name = 'core/list.html'
#     context_object_name = 'photos'
   
class PhotoSearchView(PhotoListView):
    model = Photo
    template_name = 'core/search.html'
    context_object_name = 'photos'
    photos = []
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Photo.objects.filter(name__icontains=self.args[0])
        else:
               return messages.info(self.request, "You didn't search for any photo.")
 
class PhotoTagListView(PhotoListView):
    template_name = 'core/taglist.html'
    def get_queryset(self):
        return Photo.objects.filter(tags__name=self.kwargs['tag'])


    def get_tag(self):
        return self.kwargs['tag']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.get_tag()
        return context

class PhotoDetailView(DetailView):
    template_name = 'core/detail.html'
    model = Photo
    context_object_name = 'photo'
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super(PhotoDetailView, self).get_context_data(**kwargs)
        context.update({
        'popular_posts':Photo.objects.order_by('-hit_count_generic__hits')[:3],
        })
        return context


class PhotoCreateView(CreateView,LoginRequiredMixin):
    model = Photo
    template_name = 'core/create.html'
    fields = ['title','image','tags','location']
    success_url = reverse_lazy('core:list')
    context_object_name= 'photo'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    # def post(self, request):
    #     photos = Photo.objects.all()
    #     res = response.json()
    #     photos.image = res['data'][0]['photo_url']
        
    #     return render(request, self.template_name, {'photos': photos}) 

    # def get_queryset(self):
    #     return Photo.objects.all()
    
class UserPhoto(UserPassesTestMixin):
    def get_photo(self):
        return get_object_or_404(Photo, slug=self.kwargs.get('slug'))

    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user == self.get_photo().user
        else:
            raise PermissionDenied('Sorry you are not allowed here')


class PhotoUpdateView(UserPhoto,UpdateView):
    model = Photo
    template_name = 'core/update.html'
    fields = ['title', 'image','tags']
    success_url = reverse_lazy('core:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PhotoDeleteView(UserPhoto,DeleteView):
    model = Photo
    template_name = 'core/delete.html'
    success_url = reverse_lazy('core:list')

core/templates/core/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Add photo</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mb-3">Add Photo</button>
  </form>
</div>
{% endblock body %}

core/templates/core/delete.html
{% extends 'base.html' %} 

{% block body %}
<div class="form-group mx-auto">
  <h2 class="text-center">
    You are going to <span class="text-danger">delete</span>: "<i
      >{{ photo }}</i
    >
    "
  </h2>
  <p class="text-center">Are you sure, you want to delete the photo ?</p>
  <div class="form-group">
    <form
      action=""
      method="post"
      class="d-flex flex-column align-items-center justify-content-center"
    >
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <a href="{% url 'core:detail' photo.id %}" class="btn btn-primary"
            >Cancel</a
          >
        </div>
        <div class="col">
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
      </div>
      <p>This action is irreversible</p>
    </form>
  </div>
</div>

{% endblock body %}

core/templates/core/detail.html
{% extends 'base.html' %} 
{% load hitcount_tags %}
{% block body %}
<div class="mx-auto">
  <h1 class="text-center">{{ photo.title }}</h1>
  <p class="text-center fw-light">Uploaded on: {{photo.created}} <br> By {{photo.user.username}}</p>
  {% if user == photo.user %}
    <p class="text-center">
      <span><a href="{% url 'core:update' photo.slug %}" class="text-primary px-2">Update</a></span>
      <span><a href="{% url 'core:delete' photo.slug %}" class="text-danger px-2">Delete</a></span>
    </p>
  {% endif %}
</div>
<div class="row pb-5">
  <div class="col-md-8">
    <img src="{{photo.image.url}}" alt="" width= '100%' height="100%" />
  </div>
  <div class="col-md-4">
    <h4>More about this photo:</h4>
    <span>{% get_hit_count for photo %} views</span>
    <ul class="list-group list-group-horizontal-lg list-unstyled py-4">
      {% for tag in photo.tags.all %}
        <li><a href="{% url 'core:tag' tag.slug %}" class="btn btn-sm list-group-item list-group-item-primary">{{tag.name}}</a></li>
      {% endfor %}
    </ul>
    <div class="row pb-5" id='map' style='width: 700px; height: 700px;'></div>
  <div  class="col-md-8">
<script>
  let lat,lon;
mapboxgl.accessToken = 'pk.eyJ1IjoiaWVueWVuZSIsImEiOiJjbDVwYzV3bW0wcmp6M2lvZWRmamN4cnV3In0.G3yaMn224wCZg4kS1CMbnQ';
lon = {{ photo.lon }};
lat = {{ photo.lat }};
const map = new mapboxgl.Map({
    container: 'map', // container ID
    style: 'mapbox://styles/mapbox/streets-v11', // style URL
    center: [lon, lat], // starting position [lng, lat]
    zoom: 15, // starting zoom
    projection: 'globe' // display the map as a 3D globe
});
map.on('style.load', () => {
    map.setFog({}); // Set the default atmosphere style
});
// Create a new marker.
const marker = new mapboxgl.Marker({
  color: "black",
  draggable: true
})
    .setLngLat([lon, lat])
    
    .addTo(map);
</script>
</div>
    <p>{{ photo.description }}</p>
  </div>
  


</div>

{% endblock body %}

core/templates/core/list.html
{% extends 'base.html' %} 

{% block body %}
<div class="container">
  <!-- <form method='GET'>
    <input type='text' name='q' value='{{ request.GET.q }}'>
    <input  class="button" type='submit' value="Search photos">
  </form> -->
</div>
<div class="row">
  <style>
    img:hover {
      opacity: 0.5;
    
    }
    .hovertext {
  position: relative;
  border-bottom: 1px dotted black;
}

.hovertext:before {
  content: attr(data-hover);
  visibility: hidden;
  opacity: 0;
  width: 140px;
  background-color: black;
  color: #fff;
  text-align: center;
  border-radius: 5px;
  padding: 5px 0;
  transition: opacity 1s ease-in-out;

  position: absolute;
  z-index: 1;
  left: 0;
  top: 110%;
}

.hovertext:hover:before {
  opacity: 1;
  visibility: visible;
}
  </style>
  {% for photo in photos %}
  <div class="col-lg-3 col-md-4 col-xs-6">
    <a href="{% url 'core:detail' photo.slug %}" class="d-block mb-4 h-100">
      <span class="hovertext" data-hover="{{photo.title}}">
        <img src="{{photo.image.url}}" class="img-fluid rounded" alt="{{photo.title}}" height="100%" width="100%"/> 
      </span>
      
    </a>
  </div>
  {% endfor %}
</div>


{% endblock body %}

core/templates/core/taglist.html
{% extends 'core/list.html' %}

{% block body %}

<div class="alert alert-primary">
    <h2 class="text-center">Photos with the tag {{tag}}</h2>
</div>

{{ block.super }}

{% endblock body %}

core/templates/core/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Edit photo {{photo}}</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mb-3">Edit Photo</button>
  </form>
</div>
{% endblock body %}