core/urls.py
from django.urls import path,re_path
from .views import  PhotoListView,PhotoDetailView,PhotoCreateView,PhotoUpdateView,PhotoDeleteView,PhotoTagListView,PhotoSearchView
   

app_name = 'core'
urlpatterns = [
   path('',PhotoListView.as_view(),name='list'),
    path('create/',PhotoCreateView.as_view(),name='create'),
    path('photo/<slug:slug>/',PhotoDetailView.as_view(),name='detail'),
    path('photo/<slug:slug>/update/',PhotoUpdateView.as_view(),name='update'),
    path('photo/<slug:slug>/delete/',PhotoDeleteView.as_view(),name='delete'),
    path('tag/<slug:tag>/',PhotoTagListView.as_view(),name='tag'),
    re_path(r'^search/(\w+)/$', PhotoSearchView.as_view(),name='search'),
]

photoshare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
    path('users/',include('users.urls',namespace='users')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


users/urls.py
from django.urls import path
from .views import LoginView,  SignUpView,UserLoginView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LoginView.as_view(), name='logout'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login
# Create your views here.

class SignUpView(CreateView):
    template_name = 'users/signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('users:login')


    def form_valid(self,form):
        view = super(SignUpView,self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request,user)
        return view


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    success_url = reverse_lazy('core:list')

users/templates/users/login.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}

{% block body %}

<div class="mx-auto">
  <div class="form-group">
    <form action="" method="post">
      {% csrf_token %} 
      {{ form|crispy }}
      <button type="submit" class="btn btn-danger w-100 my-3">Sign in</button>
    </form>
  </div>
  {% comment %}  Already Registered {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold">
      Don't have an account?
      <a href="{% url 'users:signup' %}" class="text-primary ml-2">Create account</a>
    </p>
  </div>
</div>
{% endblock body %}

users/templates/users/signup.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block body %}
<div class="mx-auto">
  <div class="form-group">
    <form action="" method="post">
      {% csrf_token %} 
      {{ form|crispy }}
      <button type="submit" class="btn btn-danger w-100 my-3">Create account</button>
    </form>
  </div>
  {% comment %}  Already Registered {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold">
      Already Registered?
      <a href="{% url 'users:login' %}" class="text-primary ml-2"> Login </a>
    </p>
  </div>
</div>
{% endblock body %}