core/urls.py
from django.urls import path,re_path
from .views import  PhotoListView,PhotoDetailView,PhotoCreateView,PhotoUpdateView,PhotoDeleteView,PhotoTagListView,PhotoSearchView
   

app_name = 'core'
urlpatterns = [
   path('',PhotoListView.as_view(),name='list'),
    path('create/',PhotoCreateView.as_view(),name='create'),
    path('photo/<slug:slug>/',PhotoDetailView.as_view(),name='detail'),
    path('photo/<slug:slug>/update/',PhotoUpdateView.as_view(),name='update'),
    path('photo/<slug:slug>/delete/',PhotoDeleteView.as_view(),name='delete'),
    path('tag/<slug:tag>/',PhotoTagListView.as_view(),name='tag'),
    re_path(r'^search/(\w+)/$', PhotoSearchView.as_view(),name='search'),
]

photoshare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
    path('users/',include('users.urls',namespace='users')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


users/urls.py
from django.urls import path
from .views import LoginView,  SignUpView,UserLoginView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LoginView.as_view(), name='logout'),
]

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Photo Share</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />
    
<script src='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.css' rel='stylesheet' />


    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"
    />
  </head>
  <body>
    <style>
      body{
        background-color:burlywood;
      }
    </style>
    {% include 'navbar.html' %}

    <div class="container mt-4">
    {% block body %} 

    {% endblock body %}

    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/navbar.html
<!-- templates/navbar.html -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'core:list' %}">Photo App</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div
        class="collapse navbar-collapse flex-row-reverse"
        id="navbarTogglerDemo02"
      >
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
  
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'core:create' %}">Add a photo</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#">Hi {{user.username}}</a>
          </li>
          {% else %}
  
          <li class="nav-item">
            <a href="{% url 'users:login' %}" class="btn btn-sm btn-danger"
              >Sign In</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>